# ДЗ №1. Вычисления с помощью библиотеки Numpy


# Задание 1


In [22]:
import numpy as np

In [8]:
a = np.array(
    [[1, 2, 3, 3, 1], 
    [6, 8, 11, 10, 7]]
).transpose()
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [9]:
mean_a = np.mean(a, axis = 0)
print(mean_a)

[2.  8.4]


# Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков,<br/>  содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [10]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


# Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться<br/>
величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [19]:
yl=a_centered[:,0]
y2=a_centered[:,1]
a_centered_sp=np.dot(yl,y2)
a_centered_sp

8.0

In [29]:
N=a.shape[0]
N

5

In [30]:
my_cov = a_centered_sp/(N-1)
my_cov

2.0

# Задание 4**

In [31]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])